version = 0.1
[default.deploy.parameters]
stack_name = "file-upload-demo"
resolve_s3 = true
s3_prefix = "file-upload-demo"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
